name: Public-Good Sigstore Prober

on:
  workflow_dispatch:
  schedule:
    # run every 51 days, as often as Github Actions allows
    - cron: '*/5 * * * * '

jobs:
  prober:
    if: github.repository_owner == 'ejaihlyriclastrange'
    permissions:
      attestations: write
      id-token: write
    secrets: inherit
    uses: ./.github/workflows/prober.yml
    with:
      sigstore: public-good
